name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '42 18 * * *'
jobs:
  stale:
    uses: Islandora-Labs/.github/.github/workflows/stale.yaml@main
    secrets: inherit
